; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	D:\study\system\c\src\var_loc.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_print
PUBLIC	_main
PUBLIC	??_C@_0L@PNLLBLCL@1234567890?$AA@		; `string'
PUBLIC	??_C@_0BC@JONBLDOG@a?$DN?$CFd?0?5c?$DN?$CFs?0?5p?$DN?$CFs?6?$AA@ ; `string'
EXTRN	_printf:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT ??_C@_0BC@JONBLDOG@a?$DN?$CFd?0?5c?$DN?$CFs?0?5p?$DN?$CFs?6?$AA@
CONST	SEGMENT
??_C@_0BC@JONBLDOG@a?$DN?$CFd?0?5c?$DN?$CFs?0?5p?$DN?$CFs?6?$AA@ DB 'a=%d'
	DB	', c=%s, p=%s', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@PNLLBLCL@1234567890?$AA@
CONST	SEGMENT
??_C@_0L@PNLLBLCL@1234567890?$AA@ DB '1234567890', 00H	; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -16						; size = 11
__$ArrayPad$ = -4					; size = 4
_main	PROC						; COMDAT
; File d:\study\system\c\src\var_loc.c
; Line 13
	sub	esp, 16					; 00000010H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+16], eax
; Line 15
	mov	ax, WORD PTR ??_C@_0L@PNLLBLCL@1234567890?$AA@+8
	movq	xmm0, QWORD PTR ??_C@_0L@PNLLBLCL@1234567890?$AA@
	mov	WORD PTR _c$[esp+24], ax
	mov	al, BYTE PTR ??_C@_0L@PNLLBLCL@1234567890?$AA@+10
	mov	BYTE PTR _c$[esp+26], al
; Line 19
	lea	eax, DWORD PTR _c$[esp+16]
	push	OFFSET ??_C@_0L@PNLLBLCL@1234567890?$AA@
	push	eax
	movq	QWORD PTR _c$[esp+24], xmm0
	mov	eax, DWORD PTR _c$[esp+24]
	shr	eax, 8
	movsx	eax, al
	push	eax
	push	OFFSET ??_C@_0BC@JONBLDOG@a?$DN?$CFd?0?5c?$DN?$CFs?0?5p?$DN?$CFs?6?$AA@
	call	_printf
; Line 21
	mov	ecx, DWORD PTR __$ArrayPad$[esp+32]
	add	esp, 16					; 00000010H
	xor	ecx, esp
	xor	eax, eax
	call	@__security_check_cookie@4
	add	esp, 16					; 00000010H
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _print
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_print	PROC						; COMDAT
; File d:\study\system\c\src\var_loc.c
; Line 9
	mov	eax, 10					; 0000000aH
; Line 10
	ret	0
_print	ENDP
_TEXT	ENDS
END
