; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	d:\study\system\c++\src\std\delete.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
EXTRN	??3@YAXPAX@Z:PROC				; operator delete
EXTRN	_free:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = -8						; size = 4
_a$ = -4						; size = 4
_main	PROC
; File d:\study\system\c++\src\std\delete.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 5
	mov	DWORD PTR _a$[ebp], 0
; Line 7
	mov	eax, DWORD PTR _a$[ebp]
	mov	DWORD PTR $T1[ebp], eax
	mov	ecx, DWORD PTR $T1[ebp]
	push	ecx
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
; Line 8
	mov	edx, DWORD PTR _a$[ebp]
	push	edx
	call	_free
	add	esp, 4
; Line 10
	xor	eax, eax
; Line 11
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
